# Generated by Django 3.2.5 on 2022-05-11 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
