# Generated by Django 3.2.5 on 2022-05-12 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0002_armyshop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armyshop',
            options={'managed': False},
        ),
    ]
